name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Install dependencies + dev tools
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      # 4. Lint
      - name: Lint with flake8
        run: flake8 .

      # 5. Run tests
      - name: Run pytest
        run: pytest -q
